### ISSUE TITLE
Minimap buttons problem

### ISSUE THREAD

**Issue by Yzart** [Jadei/uber-ui-classic#3]
Uber ui hide minimap buttons like the map / mail  / find button.  Addon buttons remains visible.

**Comment by Yzart** [comment]
Edit: I don't know if you changed anything, i haven't had a new update. But now i can see the mail icon on the minimap but still no map and find icon.

**Comment by Jadei** [comment]
Could you please add a screenshot ? No issue on my side

**Comment by Jadei** [comment]
Normally fix in the new release, tell me if it's ok.
