### ISSUE TITLE
Not working since Ulduar Patch

### ISSUE THREAD

**Issue by Valkyriebound** [Jadei/uber-ui-classic#5]
Hey, 
The addon isn't working since the Ulduar patch this week. Has no function at all at the moment. Would really appreciate any update please.

![WoWScrnShot_012023_095109](https://user-images.githubusercontent.com/123032913/213584002-24f4ee55-41cf-4ac3-8067-ea0ab2ed91ce.jpg)

**Comment by Jadei** [comment]
Hello,
I pushed a fix, it should be ok now.

**Comment by Valkyriebound** [comment]
Thank you very much.
